name: lint
on:
  pull_request:
    branches: [ main ]

jobs:
  golint:
    runs-on: [self-hosted, pod]
    steps:
      - uses: actions/checkout@v3

      - uses: andstor/file-existence-action@v2
        id: check_files
        with:
          files: "go.mod"

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Check golang lint
        # skip it for branch main can't pass this check
        if: ${{ github.event_name == 'pull_request' }}
        uses: qingwusunny/golangci-lint-action@v1.0.0
        with:
          version: v1.60.1
          only-new-issues: true
        env:
          GOGC: 1
          GOPROXY: https://goproxy.cn|https://proxy.golang.org|direct

  generate-check:
    runs-on: [self-hosted, pod]
    steps:
      - uses: actions/checkout@v3

      - name: make docker-generate
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: sudo make docker-generate

      - name: check if code changes
        run: sudo sh -c "git add -A && git diff HEAD --exit-code"

      - name: show message if failed
        if: ${{ failure() }}
        run: echo "::error::Please run \"make generate\" or \"make docker-generate\" before commit."

  commitlint:
    runs-on: [self-hosted, pod]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.json

  helmlint:
    runs-on: [self-hosted, pod]
    steps:
      - uses: actions/checkout@v3
      - uses: andstor/file-existence-action@v2
        id: check_files
        with:
          files: "./build/chart/Chart.yaml"
      - uses: azure/setup-helm@v3
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          version: "v3.9.4"
      - if: steps.check_files.outputs.files_exists == 'true'
        run: helm lint ./build/chart
